import type { SimulationConfig, SimulationResult, InterventionType } from './types';

// Use global loadPyodide from CDN script
declare global {
  interface Window {
    loadPyodide: (config: { indexURL: string }) => Promise<any>;
  }
}

let pyodideInstance: any = null;
let initPromise: Promise<any> | null = null;
let modelManifest: any = null;
let modelDefaults: any = null;

export interface LoadingProgress {
  stage: 'pyodide' | 'numpy' | 'package' | 'complete';
  progress: number;
}

async function fetchText(url: string): Promise<string> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }
  return response.text();
}

async function fetchJson(url: string): Promise<any> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }
  return response.json();
}

function ensureParentDirs(pyodide: any, filePath: string) {
  const parts = filePath.split('/').filter(Boolean);
  if (parts.length <= 1) return;
  let current = '';
  for (let i = 0; i < parts.length - 1; i++) {
    current += `/${parts[i]}`;
    try {
      pyodide.FS.mkdir(current);
    } catch (err: any) {
      // Ignore EEXIST across different error shapes (Pyodide/Emscripten varies).
      const message = String(err?.message || err);
      const errno = err?.errno;
      const code = err?.code;
      const isExists =
        errno === 17 ||
        code === 'EEXIST' ||
        message.includes('File exists') ||
        message.includes('EEXIST');
      if (!isExists) throw err;
    }
  }
}

function python(lines: string[]): string {
  return `${lines.join('\n')}\n`;
}

function formatUnknownError(error: unknown): string {
  if (error instanceof Error) {
    return `${error.message}${error.stack ? `\n${error.stack}` : ''}`;
  }
  if (typeof error === 'string') return error;
  if (!error || typeof error !== 'object') return String(error);

  const anyErr = error as any;
  const name = anyErr?.name ? String(anyErr.name) : 'Error';
  const message = anyErr?.message ? String(anyErr.message) : '';
  const details: Record<string, unknown> = {};
  for (const key of ['errno', 'code', 'path', 'node', 'syscall']) {
    if (anyErr?.[key] !== undefined) details[key] = anyErr[key];
  }

  const detailsStr = Object.keys(details).length ? ` ${JSON.stringify(details)}` : '';
  return `${name}${message ? `: ${message}` : ''}${detailsStr}`.trim();
}

function mkdirTree(pyodide: any, dirPath: string) {
  if (typeof pyodide?.FS?.mkdirTree === 'function') {
    pyodide.FS.mkdirTree(dirPath);
    return;
  }
  ensureParentDirs(pyodide, `${dirPath}/__dummy__`);
  try {
    pyodide.FS.mkdir(dirPath);
  } catch (err: any) {
    const message = String(err?.message || err);
    const errno = err?.errno;
    const code = err?.code;
    const isExists =
      errno === 17 ||
      code === 'EEXIST' ||
      message.includes('File exists') ||
      message.includes('EEXIST');
    if (!isExists) throw err;
  }
}

async function loadModelBundle(pyodide: any): Promise<any> {
  // Manifest is generated by `web/scripts/sync-aging-network-model.js`
  const manifest = await fetchJson('/py/model-manifest.json');
  const files: Array<{ path: string }> = manifest?.bundle?.files;
  if (!Array.isArray(files) || files.length === 0) {
    throw new Error('Invalid model manifest: bundle.files is missing/empty');
  }

  // Write bundle files into the Pyodide FS under a dedicated directory to enable `import aging_network`.
  // We avoid relying on /home/pyodide existing across Pyodide versions/environments.
  const baseDir = '/app';
  mkdirTree(pyodide, baseDir);

  for (const file of files) {
    const relPath = String(file.path || '').replace(/^\/+/, '');
    if (!relPath.endsWith('.py')) continue;
    const url = `/py/${relPath}`;
    const content = await fetchText(url);
    const fsPath = `${baseDir}/${relPath}`;
    const parentDir = fsPath.slice(0, fsPath.lastIndexOf('/'));
    mkdirTree(pyodide, parentDir);
    pyodide.FS.writeFile(fsPath, new TextEncoder().encode(content));
  }

  // Ensure baseDir is on sys.path and validate we can import the bundle.
  await pyodide.runPythonAsync(
    python([
      'import sys',
      `if ${JSON.stringify(baseDir)} not in sys.path:`,
      `    sys.path.insert(0, ${JSON.stringify(baseDir)})`,
      'import aging_network  # noqa: F401',
    ])
  );

  modelManifest = manifest;
  return manifest;
}

async function loadModelDefaults(pyodide: any): Promise<any> {
  const defaultsJson = await pyodide.runPythonAsync(
    python([
      'import json',
      'from aging_network.config import default_intervention_config, default_simulation_config',
      '',
      'inter = default_intervention_config()',
      'sim = default_simulation_config()',
      '',
      'output = {',
      '  "simulation": {',
      '    "start_age": float(sim.start_age),',
      '    "years": float(sim.years),',
      '    "dt": float(sim.dt),',
      '    "func_threshold": float(sim.func_threshold),',
      '    "death_threshold": float(sim.death_threshold),',
      '    "noise_std": float(sim.noise_std),',
      '  },',
      '  "intervention": {',
      '    "exercise_start_age": float(inter.exercise_start_age),',
      '    "exercise_recovery_gain": float(inter.exercise_recovery_gain),',
      '    "exercise_damage_reduction": float(inter.exercise_damage_reduction),',
      '    "drug_start_age": float(inter.drug_start_age),',
      '    "drug_shock_factor": float(inter.drug_shock_factor),',
      '    "organ_replacement_age": float(inter.organ_replacement_age),',
      '    "parabiosis_start_age": float(inter.parabiosis_start_age),',
      '    "parabiosis_duration": float(inter.parabiosis_duration),',
      '    "parabiosis_strength_k": float(inter.parabiosis_strength_k),',
      '    "parabiosis_recovery_gain": float(inter.parabiosis_recovery_gain),',
      '    "parabiosis_decay_reduction": float(inter.parabiosis_decay_reduction),',
      '    "parabiosis_alpha_reduction": float(inter.parabiosis_alpha_reduction),',
      '    "parabiosis_shock_damage_reduction": float(inter.parabiosis_shock_damage_reduction),',
      '  }',
      '}',
      '',
      'json.dumps(output)',
    ])
  );

  modelDefaults = JSON.parse(defaultsJson as string);
  return modelDefaults;
}

export async function initializePyodide(
  onProgress?: (progress: LoadingProgress) => void
): Promise<any> {
  if (pyodideInstance) {
    return pyodideInstance;
  }

  if (initPromise) {
    return initPromise;
  }

  initPromise = (async () => {
    try {
      // Wait for window.loadPyodide to be available from CDN script
      while (typeof window === 'undefined' || !window.loadPyodide) {
        await new Promise(resolve => setTimeout(resolve, 100));
      }

      // Load Pyodide
      onProgress?.({ stage: 'pyodide', progress: 0.25 });
      const pyodide = await window.loadPyodide({
        indexURL: 'https://cdn.jsdelivr.net/pyodide/v0.29.0/full/',
      });

      // Load NumPy
      onProgress?.({ stage: 'numpy', progress: 0.5 });
      await pyodide.loadPackage('numpy');

      // Load the aging_network model bundle generated from src/aging_network
      onProgress?.({ stage: 'package', progress: 0.75 });
      await loadModelBundle(pyodide);
      await loadModelDefaults(pyodide);

      onProgress?.({ stage: 'complete', progress: 1.0 });
      pyodideInstance = pyodide;
      return pyodide;
    } catch (error) {
      initPromise = null;
      console.error('Pyodide initialization failed:', error);
      throw new Error(`Failed to initialize Pyodide: ${formatUnknownError(error)}`);
    }
  })();

  return initPromise;
}

export async function runSimulation(
  intervention: InterventionType,
  config: Partial<SimulationConfig> = {}
): Promise<SimulationResult> {
  const pyodide = await initializePyodide();

  const configStr = JSON.stringify(config);
  const interventionStr = JSON.stringify(intervention);

  const pythonCode = python([
    'import json',
    'import numpy as np',
    '',
    `config = json.loads(${JSON.stringify(configStr)})`,
    'from aging_network.config import SimulationConfig',
    'from aging_network.simulation import run_sim',
    '',
    'sim_config = SimulationConfig(**config) if config else None',
    '',
    `result = run_sim(${interventionStr}, sim_config=sim_config)`,
    '',
    'ages = result.age',
    'X_hist = result.X_hist',
    'D_hist = result.D_hist',
    '',
    'healthspan = float(result.healthspan) if result.healthspan is not None else float(ages[-1])',
    'lifespan = float(result.lifespan) if result.lifespan is not None else float(ages[-1])',
    '',
    'output = {',
    '    "ages": ages.tolist(),',
    '    "X": X_hist.tolist(),',
    '    "D": D_hist.tolist(),',
    '    "healthspan": healthspan,',
    '    "lifespan": lifespan,',
    '    "mean_X": np.mean(X_hist, axis=1).tolist(),',
    '    "mean_D": np.mean(D_hist, axis=1).tolist(),',
    '    "cause_of_death": int(result.cause_of_death) if result.cause_of_death is not None else None,',
    '}',
    '',
    'json.dumps(output)',
  ]);

  try {
    const resultJson = await pyodide.runPythonAsync(pythonCode);
    const result: SimulationResult = JSON.parse(resultJson as string);
    return result;
  } catch (error) {
    throw new Error(`Simulation failed: ${error}`);
  }
}

export function isPyodideReady(): boolean {
  return pyodideInstance !== null;
}

export function getModelManifest(): any {
  return modelManifest;
}

export function getModelDefaults(): any {
  return modelDefaults;
}
