"""Aging network model (web bundle).

This file is generated by web/scripts/sync-aging-network-model.js.
It intentionally avoids importing plotting utilities (matplotlib) because the web
UI renders charts in JavaScript.
"""

from .config import (
    DEFAULT_SCENARIOS,
    SimulationConfig,
    SystemConfig,
    default_intervention_config,
    default_simulation_config,
    default_system_config,
)
from .simulation import SimulationResult, run_all_scenarios, run_many, run_sim

__all__ = [
    "DEFAULT_SCENARIOS",
    "SimulationConfig",
    "SystemConfig",
    "SimulationResult",
    "default_simulation_config",
    "default_system_config",
    "default_intervention_config",
    "run_sim",
    "run_many",
    "run_all_scenarios",
]
